"""Freeze the scoped v7 stage order captured before the v8 turn-stage refactor.

The expected sequences were recorded from commit d5ccec0 with the scripted clients. The
scoped planner keeps them until it is removed; a change here means scoped behavior changed.
"""

from __future__ import annotations

from typing import Any

import pytest
from test_pipeline import _coordinator

EXPECTED = {
    "detailed_repair": {
        "generator_a": [
            "question_intent",
            "question_fit",
            "requirement_extraction",
            "claim_inventory",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "claim_inventory",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "question_intent",
            "question_fit",
            "requirement_extraction",
            "claim_inventory",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
        ],
        "generator_b": [
            "evidence_extraction",
            "candidate_binding",
            "question_generation",
            "question_intent",
            "question_fit",
            "requirement_extraction",
            "answer_generation",
            "claim_inventory",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "answer_repair",
            "claim_inventory",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "candidate_binding",
            "question_generation",
            "question_intent",
            "question_fit",
            "requirement_extraction",
            "answer_generation",
            "claim_inventory",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
            "rubric_item",
        ],
        "selector": ["instruction_selection", "instruction_selection"],
        "status": "QUALITY_CANDIDATE",
        "turns": ["COMMITTED", "COMMITTED"],
    },
    "holistic_internal_reference_first": {
        "generator_a": [
            "question_intent",
            "question_fit",
            "holistic_review",
            "question_intent",
            "question_fit",
            "holistic_review",
        ],
        "generator_b": [
            "evidence_extraction",
            "candidate_binding",
            "question_generation",
            "question_generation",
            "question_intent",
            "question_fit",
            "answer_generation",
            "holistic_review",
            "candidate_binding",
            "question_generation",
            "question_generation",
            "question_intent",
            "question_fit",
            "answer_generation",
            "holistic_review",
        ],
        "selector": ["instruction_selection", "instruction_selection"],
        "status": "QUALITY_CANDIDATE",
        "turns": ["COMMITTED", "COMMITTED"],
    },
    "holistic_repeat_question": {
        "generator_a": ["question_intent", "question_fit", "holistic_review"],
        "generator_b": [
            "evidence_extraction",
            "candidate_binding",
            "question_generation",
            "question_intent",
            "question_fit",
            "answer_generation",
            "holistic_review",
            "candidate_binding",
            "question_generation",
            "question_generation",
        ],
        "selector": ["instruction_selection", "instruction_selection"],
        "status": "REJECTED",
        "turns": ["COMMITTED"],
    },
    "holistic_success": {
        "generator_a": [
            "question_intent",
            "question_fit",
            "holistic_review",
            "question_intent",
            "question_fit",
            "holistic_review",
        ],
        "generator_b": [
            "evidence_extraction",
            "candidate_binding",
            "question_generation",
            "question_intent",
            "question_fit",
            "answer_generation",
            "holistic_review",
            "candidate_binding",
            "question_generation",
            "question_intent",
            "question_fit",
            "answer_generation",
            "holistic_review",
        ],
        "selector": ["instruction_selection", "instruction_selection"],
        "status": "QUALITY_CANDIDATE",
        "turns": ["COMMITTED", "COMMITTED"],
    },
}

SCENARIOS: dict[str, dict[str, Any]] = {
    "holistic_success": {"evaluation_mode": "holistic"},
    "detailed_repair": {"fail_first_rating": True},
    "holistic_repeat_question": {"evaluation_mode": "holistic", "repeat_question": True},
    "holistic_internal_reference_first": {
        "evaluation_mode": "holistic",
        "internal_reference_question": "first",
    },
}


@pytest.mark.parametrize("name", sorted(SCENARIOS))
def test_scoped_stage_sequences_match_pre_refactor_capture(tmp_path, image_artifact, name) -> None:
    image, root = image_artifact
    coordinator, store, selector, generator_a, generator_b = _coordinator(
        tmp_path, **SCENARIOS[name]
    )
    try:
        conversation = coordinator.synthesize_image(image, root)
    finally:
        store.close()
    observed = {
        "status": conversation.status,
        "turns": [turn.status for turn in conversation.turns],
        "selector": [stage for stage, _ in selector.calls],
        "generator_a": [stage for stage, _ in generator_a.calls],
        "generator_b": [stage for stage, _ in generator_b.calls],
    }
    assert observed == EXPECTED[name]
